In [13]:
# Importing the necessary libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [14]:
# Load the dataset
filepath = 'real_estate_data.csv'  # Specify the correct file path
data = pd.read_csv(filepath)

In [15]:
# Display the first few rows of the data
data.head(10)

,Full Address,Project Name,Primary Photo,First Two Photos,Floor Plan,Property Type,For Sale or For Rent,Asking Price (PHP),Rent Price (PHP),Price per Sqm (PHP),...,Badges,More Photos,Video Tour,Related Project,Broker,Nearness to landmarks/key locations,Similar Properties,Commission PHP,Commission %,Price vs Zonal Value
0,"30188 Johnson Green\nBuckland, WV 59978",Richardson-Reid,theory.jpeg,"short.jpg,decide.png",contain.odt.pdf,Townhouse,For Sale,11956980.0,NaN,170814,...,Affordable,"although.jpeg,move.gif",reach.avi,Johnston-Tran,Jennifer Owens,12 mins to UP Diliman,Makati Prime Tower,597849.00,5,Comparable
1,"589 Shannon Squares\nEast Kristenland, AK 16494",Good Inc,trial.jpg,"later.jpeg,pass.jpg",build.mp4.pdf,Townhouse,For Sale,14844518.0,NaN,125801,...,New Listing,"successful.jpeg,use.bmp",much.avi,Lewis Group,Kenneth Rose,14 mins to IT Park,Tower 1,742225.90,5,Comparable
2,"24228 Julia Forge\nWest Jerry, ME 05645",Reynolds PLC,check.bmp,"outside.jpg,scientist.bmp",officer.avi.pdf,Condominium,For Sale,18680627.0,NaN,134393,...,Prime Location,"hear.png,city.jpg",threat.webm,"Sanders, Smith and Alexander",Rebecca Marshall,8 mins to Festival Mall,Makati Prime Tower,934031.35,5,Comparable
3,"377 Megan Way\nShawnfurt, ND 51619",Diaz-Owens,lead.gif,"available.jpg,seat.bmp",executive.webm.pdf,House and Lot,For Sale,9008224.0,NaN,101216,...,Prime Location,"thought.gif,quality.bmp",scientist.mov,"Terry, Watts and Nolan",Mark Smith,1 mins to IT Park,Tower 1,450411.20,5,Higher
4,"221 Carr Extensions\nJarvisborough, UT 82903","Dunn, Johnson and Williams",strong.png,"wonder.jpeg,consider.jpeg",ago.odt.pdf,Townhouse,For Rent,NaN,90827.0,96418,...,New Listing,"give.jpeg,peace.jpeg",feel.mov,"Barker, Wall and Gardner",Mary Robinson,8 mins to Megamall,Village A,1816.54,2,Lower
5,"156 Christopher Shore Suite 255\nPort Jeremy, ...","Baker, Glass and Mueller",town.jpeg,"audience.gif,start.tiff",quite.jpeg.pdf,Apartment,For Rent,NaN,83268.0,163939,...,Affordable,"also.png,role.png",try.mov,Harrison PLC,Billy Houston,11 mins to IT Park,Makati Prime Tower,1665.36,2,Comparable
6,"41933 Glenn Forges\nMcdanieltown, HI 82405",Taylor and Sons,strategy.bmp,"moment.jpeg,more.tiff",gas.mp3.pdf,House and Lot,For Rent,NaN,82189.0,164945,...,Prime Location,"enter.tiff,watch.tiff",particularly.webm,Burton-Martinez,Nicole Greene,1 mins to Festival Mall,Tower 1,1643.78,2,Comparable
7,"74615 Green Inlet\nSouth Travismouth, OH 85875","Cruz, Smith and Duncan",admit.bmp,"really.jpeg,everybody.tiff",high.json.pdf,Townhouse,For Sale,14835744.0,NaN,137368,...,New Listing,"take.gif,high.png",without.mp4,"Willis, Henry and Adams",Morgan Torres,6 mins to Megamall,Village A,741787.20,5,Higher
8,Unit 5876 Box 2263\nDPO AA 79389,Stevens-Cruz,nation.gif,"place.tiff,majority.gif",more.avi.pdf,Townhouse,For Rent,NaN,19864.0,104310,...,Hot Property,"including.bmp,send.bmp",deal.webm,"Fuller, Wu and Anderson",Lisa Reyes,9 mins to UP Diliman,Makati Prime Tower,397.28,2,Higher
9,"56337 Alvarado Street\nPort Danielle, OK 84504",Miller-Mosley,risk.bmp,"risk.gif,decade.bmp",involve.mp3.pdf,Condominium,For Rent,NaN,50211.0,87727,...,Affordable,"list.gif,page.jpg",among.mp4,Boyer-Marshall,Oscar Cameron,2 mins to Megamall,Village A,1004.22,2,Comparable

In [16]:
# Display summary statistics of the dataset
data.describe()

,Asking Price (PHP),Rent Price (PHP),Price per Sqm (PHP),Down payment Php,Down payment %,Advanced Payment (months),Security Deposit (months),Minimum Rent duration (months),Size (sqm),Commission PHP,Commission %
count,1.012000e+03,988.000000,2000.000000,1.012000e+03,1012.0,988.000000,988.000000,988.000000,2000.000000,2.000000e+03,2000.000000
mean,2.021813e+07,56510.016194,124601.245000,4.043625e+06,20.0,2.038462,2.013158,15.085020,157.658500,5.120769e+05,3.518000
std,1.282985e+07,25007.599450,42779.138786,2.565970e+06,0.0,0.811854,0.804514,5.487285,80.024201,6.805340e+05,1.500267
min,1.067440e+06,15155.000000,50012.000000,2.134880e+05,20.0,1.000000,1.000000,6.000000,20.000000,3.031000e+02,2.000000
25%,9.738329e+06,33914.250000,87360.250000,1.947666e+06,20.0,1.000000,1.000000,10.000000,89.000000,1.129845e+03,2.000000
50%,1.809309e+07,55638.000000,124403.000000,3.618618e+06,20.0,2.000000,2.000000,15.000000,156.000000,1.099024e+05,5.000000
75%,2.912402e+07,77803.750000,160445.750000,5.824803e+06,20.0,3.000000,3.000000,20.000000,225.000000,9.173842e+05,5.000000
max,5.832106e+07,99847.000000,199982.000000,1.166421e+07,20.0,3.000000,3.000000,24.000000,300.000000,2.916053e+06,5.000000

In [17]:
# Check for missing values
missing_data = data.isnull().sum()
print("Missing values in each column:\n", missing_data)

# # Option 1: Drop rows with missing values
# data_cleaned = data.dropna()

# # Option 2: Fill missing values with the median of each column
# # data_cleaned = data.fillna(data.median())

# # Option 3: Fill missing categorical data with the most frequent value (mode)
# # data_cleaned['column_name'] = data_cleaned['column_name'].fillna(data_cleaned['column_name'].mode()[0])

# # Display cleaned data
# data_cleaned.head()

Missing values in each column:
 Full Address                              0
Project Name                              0
Primary Photo                             0
First Two Photos                          0
Floor Plan                                0
Property Type                             0
For Sale or For Rent                      0
Asking Price (PHP)                      988
Rent Price (PHP)                       1012
Price per Sqm (PHP)                       0
Down payment Php                        988
Down payment %                          988
Advanced Payment (months)              1012
Security Deposit (months)              1012
Minimum Rent duration (months)         1012
Generic Address                           0
Approximated GPS Pin                      0
Size (sqm)                                0
Property Specifications                   0
Property Features                         0
Property Category                         0
Created / Updated Date                    0
Full Description                          0
Developer                                 0
Verified Status                           0
Badges                                    0
More Photos                               0
Video Tour                                0
Related Project                           0
Broker                                    0
Nearness to landmarks/key locations       0
Similar Properties                        0
Commission PHP                            0
Commission %                              0
Price vs Zonal Value                      0
dtype: int64

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 35 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Full Address                         2000 non-null   object
 1   Project Name                         2000 non-null   object
 2   Primary Photo                        2000 non-null   object
 3   First Two Photos                     2000 non-null   object
 4   Floor Plan                           2000 non-null   object
 5   Property Type                        2000 non-null   object
 6   For Sale or For Rent                 2000 non-null   object
 7   Asking Price (PHP)                   1012 non-null   float64
 8   Rent Price (PHP)                     988 non-null    float64
 9   Price per Sqm (PHP)                  2000 non-null   int64
 10  Down payment Php                     1012 non-null   float64
 11  Down payment %                       1012 non-null   float64
 12  Advanced Payment (months)            988 non-null    float64
 13  Security Deposit (months)            988 non-null    float64
 14  Minimum Rent duration (months)       988 non-null    float64
 15  Generic Address                      2000 non-null   object
 16  Approximated GPS Pin                 2000 non-null   object
 17  Size (sqm)                           2000 non-null   int64
 18  Property Specifications              2000 non-null   object
 19  Property Features                    2000 non-null   object
 20  Property Category                    2000 non-null   object
 21  Created / Updated Date               2000 non-null   object
 22  Full Description                     2000 non-null   object
 23  Developer                            2000 non-null   object
 24  Verified Status                      2000 non-null   object
 25  Badges                               2000 non-null   object
 26  More Photos                          2000 non-null   object
 27  Video Tour                           2000 non-null   object
 28  Related Project                      2000 non-null   object
 29  Broker                               2000 non-null   object
 30  Nearness to landmarks/key locations  2000 non-null   object
 31  Similar Properties                   2000 non-null   object
 32  Commission PHP                       2000 non-null   float64
 33  Commission %                         2000 non-null   int64
 34  Price vs Zonal Value                 2000 non-null   object
dtypes: float64(8), int64(3), object(24)
memory usage: 547.0+ KB